version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=postgres
      - DB_USER=QuickMarketsDB
      - DB_PASSWORD=Ruster1392!@
      - DB_HOST=quickmarkets-db.cev286m487pi.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
    command: >
      sh -c "python manage.py migrate --settings=server.settings &&
             gunicorn --bind 0.0.0.0:8000 --workers 2 server.wsgi:application"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.simple
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend

