# Generated by Django 5.2 on 2025-04-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_stock_industry_alter_stock_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='type',
        ),
    ]
