# Generated by Django 5.2 on 2025-04-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_remove_etf_name_alter_etf_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='etf',
            name='ticker',
            field=models.CharField(max_length=4),
        ),
    ]
