# Generated by Django 4.2.20 on 2025-05-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_stock_prev_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='prev_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
