# Generated by Django 5.2.1 on 2025-05-10 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stockName', models.CharField(default='', max_length=50)),
                ('currPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('sectorType', models.CharField(default='', max_length=50)),
                ('volatility', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('avgReturn', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('passwordHash', models.CharField(max_length=255)),
                ('cashBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closingPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('stock', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='simulator.stock')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharesAmount', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('averageCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='simulator.stock')),
                ('user', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='simulator.user')),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
