# Generated by Django 5.2 on 2025-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_stock_avgreturn_stock_volatility_alter_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='avgReturn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volatility',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
