# Generated by Django 5.2.1 on 2025-05-10 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_etf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etf',
            name='id',
        ),
        migrations.AlterField(
            model_name='etf',
            name='ticker',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sectorType',
            field=models.ForeignKey(db_column='etf_ticker', on_delete=django.db.models.deletion.CASCADE, to='simulator.etf'),
        ),
    ]
