# Generated by Django 5.2 on 2025-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_alter_stock_avgreturn_alter_stock_volatility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='avgReturn',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volatility',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
