# Generated by Django 5.2.1 on 2025-05-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_remove_etf_id_alter_etf_ticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='prev_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
