# Generated by Django 5.2 on 2025-04-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_alter_stock_avgreturn_alter_stock_volatility'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(default='AI', max_length=15),
        ),
    ]
