# Generated by Django 5.2 on 2025-04-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='Tech', max_length=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(default='Stock', max_length=15),
        ),
    ]
