# Generated by Django 5.2.1 on 2025-05-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_stock_prev_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='prev_price',
            new_name='prevPrice',
        ),
    ]
