# Generated by Django 5.2.1 on 2025-05-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_rename_prev_price_stock_prevprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockpricehistory',
            old_name='stock',
            new_name='stockTicker',
        ),
        migrations.AlterUniqueTogether(
            name='stockpricehistory',
            unique_together={('stockTicker', 'date')},
        ),
    ]
