# Generated by Django 5.2 on 2025-04-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_remove_stock_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volatility', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('avgReturn', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('industry', models.CharField(default='Tech', max_length=15)),
            ],
        ),
    ]
