# Generated by Django 5.2 on 2025-04-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_etf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etf',
            name='name',
        ),
        migrations.AlterField(
            model_name='etf',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
