# Generated by Django 5.2.1 on 2025-05-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='stock',
            new_name='stockTicker',
        ),
    ]
