# Generated by Django 4.2.23 on 2025-09-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_rename_stock_transaction_stockticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='simulator.user')),
            ],
            options={
                'unique_together': {('user', 'ticker')},
            },
        ),
    ]
