# Generated by Django 4.2.23 on 2025-09-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0010_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='addedAt',
        ),
    ]
