# Generated by Django 4.2.20 on 2025-05-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0010_etf_name_alter_etf_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='prev_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
