# Generated by Django 4.2.23 on 2025-09-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_remove_watchlist_addedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricehistory',
            name='dayChange',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='openingPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
