# Generated by Django 4.2.23 on 2025-09-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_stockpricehistory_daychange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpricehistory',
            name='volume',
        ),
    ]
