# Generated by Django 4.2.23 on 2025-09-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0013_remove_volume_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.IntegerField(default=1)),
                ('start_date', models.DateField(default='2024-01-01')),
            ],
            options={
                'verbose_name': 'Simulation Day',
                'verbose_name_plural': 'Simulation Days',
            },
        ),
    ]
