# Generated by Django 4.2.23 on 2025-09-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0014_add_simulation_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('portfolioValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cashBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stockValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='simulator.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
