# Generated by Django 4.2.23 on 2025-09-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0015_portfoliohistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliohistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.user'),
        ),
    ]
