# Generated by Django 4.2.23 on 2025-09-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0017_auto_20250930_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.user'),
        ),
    ]
