# Generated by Django 4.2.23 on 2025-09-30 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0018_watchlist_addedat_alter_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationday',
            name='day_interval_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='simulationday',
            name='last_day_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
