# Generated by Django 4.2.23 on 2025-10-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0019_simulationday_day_interval_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('last_end_of_day_call', models.DateTimeField(blank=True, null=True)),
                ('last_during_day_call', models.DateTimeField(blank=True, null=True)),
                ('total_seconds_elapsed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SimulationDay',
        ),
    ]
