# Generated by Django 4.2.23 on 2025-10-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0020_simulationtimer_delete_simulationday'),
    ]

    operations = [
    ]
