# Generated by Django 4.2.23 on 2025-10-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0021_auto_20251001_1308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfoliohistory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stockpricehistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='simulationtimer',
            name='current_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliohistory',
            unique_together={('user', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='stockpricehistory',
            unique_together={('stockTicker', 'day')},
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stockpricehistory',
            name='date',
        ),
    ]
