# Generated by Django 4.2.23 on 2025-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0022_alter_portfoliohistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationtimer',
            name='time_until_next_day',
            field=models.IntegerField(default=15),
        ),
    ]
